services:
  web:
    build: .

    volumes:
      - db-volume-staging:/app/db
      # this volume is shared with nginx container
      - files-volume-staging:/app/nginx

    env_file: "./.env-staging"

    networks:
      - yt-summarizer-network

    command: >
      sh -c "python manage.py migrate &&
             # collect static files (creates STATIC_ROOT path if not already exits)
             python manage.py collectstatic --no-input &&
             # create folder for media files if not already exist
             mkdir -p /app/nginx/media/thumbnails &&
             # start django app 
             gunicorn -c ./project_config/gunicorn.py"

    restart: unless-stopped

    container_name: yt-summarizer-staging

  nginx:
    build: ./nginx

    volumes:
      # this volume is shared with django container (read-only)
      - files-volume-staging:/usr/share/nginx/html:ro

    depends_on:
      - web

    networks:
      - yt-summarizer-network

    restart: unless-stopped

    container_name: yt-summarizer-nginx-staging

  cloudflare_tunnel:
    image: cloudflare/cloudflared:1449-569a7c3c9ed0

    env_file: "./.env-staging"

    command: tunnel --no-autoupdate run

    networks:
      - yt-summarizer-network

    restart: unless-stopped

    container_name: yt-summarizer-cf-tunnel-staging

volumes:
  db-volume-staging:
  files-volume-staging:

networks:
  yt-summarizer-network:
    name: yt-summarizer-network
    external: false
