AWSTemplateFormatVersion: '2010-09-09'
Description: 'Template 2 of 3: Cloudflare Prefix List and Security Group Setup'

# Add a Parameter to capture the network stack name
Parameters:
  VpcStackName:
    Type: String
    Default: staging-vpc

Resources:
  CloudflareIpPrefixList:
    Type: AWS::EC2::PrefixList
    Properties:
      AddressFamily: IPv4
      MaxEntries: 15
      PrefixListName: cloudflare-ipv4-ranges
      Entries:
        - { Cidr: 162.158.0.0/15, Description: "Cloudflare Range" }
        - { Cidr: 103.21.244.0/22, Description: "Cloudflare Range" }
        - { Cidr: 188.114.96.0/20, Description: "Cloudflare Range" }
        - { Cidr: 198.41.128.0/17, Description: "Cloudflare Range" }
        - { Cidr: 197.234.240.0/22, Description: "Cloudflare Range" }
        - { Cidr: 172.64.0.0/13, Description: "Cloudflare Range" }
        - { Cidr: 173.245.48.0/20, Description: "Cloudflare Range" }
        - { Cidr: 104.16.0.0/13, Description: "Cloudflare Range" }
        - { Cidr: 103.31.4.0/22, Description: "Cloudflare Range" }
        - { Cidr: 190.93.240.0/20, Description: "Cloudflare Range" }
        - { Cidr: 103.22.200.0/22, Description: "Cloudflare Range" }
        - { Cidr: 108.162.192.0/18, Description: "Cloudflare Range" }
        - { Cidr: 141.101.64.0/18, Description: "Cloudflare Range" }
        - { Cidr: 104.24.0.0/14, Description: "Cloudflare Range" }
        - { Cidr: 131.0.72.0/22, Description: "Cloudflare Range" }

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow inbound HTTPS from Cloudflare Prefix List and SSH globally
      VpcId:
        Fn::ImportValue:
          Fn::Sub: "${VpcStackName}-VpcId"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          SourcePrefixListId: !Ref CloudflareIpPrefixList
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

Outputs:
  ExportedSecurityGroupId:
    Description: The ID of the Cloudflare-restricted security group
    Value: !Ref InstanceSecurityGroup
    Export:
      Name: !Sub "${AWS::StackName}-CloudflareSecurityGroupId"