# Generated by Django 5.1 on 2025-07-28 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ytsummary',
            name='thumbnail',
            field=models.ImageField(default='thumbnails/thumbnail_not_found.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='ytsummary',
            name='title',
            field=models.CharField(default='N/A', max_length=255),
        ),
    ]
