# Generated by Django 5.1 on 2025-08-12 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer_app', '0002_add_title_and_thumbnail_fields_YTSummary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ytsummary',
            name='title',
            field=models.CharField(default='Title Not Available', max_length=255),
        ),
    ]
