# Generated by Django 5.1 on 2025-08-26 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer_app', '0003_change_default_title_YTSummary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ytsummary',
            options={'verbose_name_plural': 'YTSummaries'},
        ),
        migrations.AlterField(
            model_name='ytsummary',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
