# Generated by Django 5.1 on 2025-12-30 02:08

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer_app', '0004_auto_now_add_in_created_on_YTSummary'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='ytsummary',
            managers=[
                ('summaries', django.db.models.manager.Manager()),
            ],
        ),
    ]
