# workflow to run ci tests before accepting pull requests in main branch

name: CI

on:
  # this workflow runs on pull_request to main branch
  pull_request:
    branches: [main]

concurrency: # abort jobs if new code arrives to the same pull request
  group: ci-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  build-test-and-push-image-to-GHCR:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write # necessary for actionlint action
      packages: write # necessary to push image to GHCR

    env:
      IMAGE: ghcr.io/${{github.repository}}

    steps:
      - name: checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: run actionlint action
        uses: devops-actions/actionlint@9fb9c192862f19e684586ca84b500461bcd8a541 #v0.1.12

      - name: Log in to GHCR
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee #v4.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 #v4.1.0

      - name: build and load docker image
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf #v7.2.0
        with:
          context: .
          push: false # do not push the image
          load: true # make the image available to the runner's docker engine
          tags: |
            ${{env.IMAGE}}:test-env
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: create logs folder (necessary to run unit tests)
        run: |
          mkdir -p logs
          chmod -R 777 logs      

      - name: run unit tests
        run: |
          docker run --rm -e DJANGO_SECRET_KEY="${{secrets.DJANGO_SECRET_KEY}}" -v "${PWD}/logs:/app/logs" \
          "${{env.IMAGE}}:test-env" sh -c "python manage.py test --no-input -b -v 2" > test_results.txt 2>&1

      - name: show test results in job summary
        if: always() # runs even if the last step fails
        uses: ./.github/actions/show-test-results
        with:
          results-file: test_results.txt

      # NOTE: for here on, all steps must test for success() to prevent execution if tests failed
      - name: prepare tags for docker image (if tests pass)
        if: success() # <-- Crucial: prevents execution of this step if the tests failed
        id: image_tags
        uses: docker/metadata-action@80c7e94dd9b9319bd5eb7a0e0fe9291e23a2a2e9 # v6.1.0
        with:
          images: ${{env.IMAGE}}
          tags: |
            # automatically outputs standard 7-char short SHA from commit
            type=sha
            # also add 'latest' tag
            type=raw,value=latest

      - name: push Image to GHCR (if tests pass)
        if: success() # <-- Crucial: Prevents pushing if the tests failed
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf #v7.2.0
        with:
          context: .
          push: true # push image to GHCR
          tags: |
            ${{ steps.image_tags.outputs.tags }}
          cache-from: type=gha
