# workflow to run CI tests before accepting pull requests in main branch

name: CI

on:
  # this workflow runs on pull_request to main branch and on workflow_dispatch on any branch
  pull_request:
    branches: [main]

  workflow_dispatch:

concurrency: # abort jobs if new code arrives to the same pull request
  group: ci-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write # necessary for actionlint action

    env:
      IMAGE: ${{github.repository}}

    steps:
      - name: checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: run actionlint action
        uses: devops-actions/actionlint@9fb9c192862f19e684586ca84b500461bcd8a541 #v0.1.12

      - name: build docker image
        uses: ./.github/actions/build-push-docker-image
        with:
          image-name: ${{env.IMAGE}}
          push-image: 'false'

      - name: create logs folder (necessary to run unit tests)
        run: |
          mkdir -p logs
          chmod -R 777 logs      

      - name: run unit tests
        run: |
          docker run --rm -e DJANGO_SECRET_KEY="${{secrets.DJANGO_SECRET_KEY}}" -v "${PWD}/logs:/app/logs" \
          "${{env.IMAGE}}" sh -c "python manage.py test --no-input -b -v 2" > test_results.txt 2>&1

      - name: show test results in job summary
        if: always() # runs even if the last step fails
        uses: ./.github/actions/show-test-results
        with:
          results-file: test_results.txt
