# workflow to run tests before accepting pull requests in main branch

name: Run Tests

on: [pull_request, workflow_dispatch]

jobs:
  
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v2
        
      - name: create .env file for docker compose
        run: |
          echo "DEEPSEEK_API_KEY=${{secrets.DEEPSEEK_API_KEY}}" > .env
          echo "DJANGO_SECRET_KEY=${{secrets.DJANGO_SECRET_KEY}}" >> .env
          echo "DJANGO_RECAPTCHA_PUBLIC_KEY=${{secrets.DJANGO_RECAPTCHA_PUBLIC_KEY}}" >> .env
          echo "DJANGO_RECAPTCHA_PRIVATE_KEY=${{secrets.DJANGO_RECAPTCHA_PRIVATE_KEY}}" >> .env
                      
      - name: Run unit tests
        run: docker compose run --rm web sh -c "python manage.py test"
        